### ISSUE TITLE
📝 TODO: Clean up / setup

### ISSUE THREAD

**Issue by w3cj** [w3cj/wikipedia-clean-dark-green#1]
Initial updates were hacked together. Clean up should include:

- [x] Research how to do local development for a stylus extension
- [x] Install / setup css linter, postcss and vite
- [x] Extract variables to :root
- [ ] Update code to be grouped by section / separate files
- [ ] Reduce duplication of selectors and rules
